# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for NVR
LUCI_DEPENDS:=+ffmpeg
LUCI_PKGARCH:=all
PKG_NAME:=luci-app-nvr
PKG_VERSION:=20240614
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature




